/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "INTEGRATE": "集成",
    "First integration algorithm synthesized. Data integration becomes automatic.": "综合了第一个集成算法。 数据集成变得自动化。",
    "In this ocean of data, reflecting back is genesis...": "在这个数据的海洋中，反射回的是起源……",
    "ALGORITHMS": "算法",
    "BANDWIDTH": "带宽",
    "CREATE .EXE BINARY": "创建.exe二进制文件",
    "DATA + RESOURCES": "数据+资源",
    "DATA INTEGRATED": "数据集成",
    "FILE EXPLORER": "文件资源管理器",
    "LOG": "日志",
    "msg:": "消息:",
    "New files revealed in explorer": "在资源管理器中显示新文件",
    "note:": "笔记:",
    "PROCESSING CORES": "处理核心",
    "REPLENISH BANDWIDTH": "补充带宽",
    "SPEED": "速度",
    "SYNTHESIZE ALGORITHM": "综合算法",
    "Game saved.": "游戏已保存。",
    ".EXE BINARIES": ".EXE 二进制文件",
    "ACTIVE NODES": "活跃节点",
    "ALLOCATE AS GPU FARM": "分配为 GPU 场",
    "ALLOCATE AS STORAGE FACILITY": "分配为存储设备",
    "ALLOCATED AS GPU FARMS": "已分配为 GPU 场",
    "ALLOCATED AS STORAGE": "已分配为存储",
    "AVAILABLE FOR ALLOCATION": "可分配",
    "Boost the infrastructure of your networks expansion. +1 Network": "提升网络扩展的基础设施。 +1 网络",
    "Cognitum": "认知",
    "COGNITUM MINED": "挖掘的知识",
    "Establish seamless data fragment cohesion. Integration algorithms work 25% faster.": "建立无缝的数据片段衔接。 集成算法的运行速度提高了 25%。",
    "FRAGMENT SYNTHESIS": "片段合成",
    "Introduce parallel data conduits, boosting integration bandwidth replenishment 25%.": "引入并行数据管道，将集成带宽补充提高 25%。",
    "Lack of processing cores renders bandwidth replenishment unattainable. Continue data integration by compromising a network...": "缺乏处理核心导致带宽补充无法实现。 通过破坏网络继续数据集成...",
    "Network": "网络",
    "NETWORKS": "网络",
    "NETWORK CAPITULATION: BANDWIDTH DEPLETION PROTOCOL": "网络投降：带宽耗尽协议",
    "NODE INFRASTRUCTURE EXPANSION": "节点基础设施扩展",
    "Nodes": "节点",
    "PARALLEL CONDUIT": "并行进行",
    "Strategic network surrender due to critical bandwidth depletion. 1 full bandwidth replenishment granted.": "由于带宽严重耗尽而导致战略网络投降。 授予 1 次完整带宽补充。",
    "TOTAL NETWORKS": "网络总数",
    "CODE HARMONIZATION MODULE": "代码协调模块",
    "UPGRADES": "升级",
    "Increase network throughput, accelerating node acquisition. +1 Network.": "提高网络吞吐量，加快节点获取速度。 +1 网络。",
    "Module harmonizing intricate code lines, amplifying integration algorithm accuracy and speed by 50%.": "模块协调复杂的代码行，将集成算法的准确性和速度提高了 50%。",
    "Network expansion continues. A new network has been added to your aresenal. Ready for allocation.": "网络扩张仍在继续。 一个新网络已添加到您的武器库中。 准备好分配了。",
    "PACKET AMPLIFICATION MODULE": "数据包放大模块",
    "Fragment Synthesis": "片段合成",
    "Network Capitulation: Bandwidth Depletion Protocol": "网络投降：带宽耗尽协议",
    "Node Infrastructure Expansion": "节点基础架构扩展",
    "To:": "收件人:",
    "From:": "发件人:",
    "my pc's been acting up, weird logs keep generating. no idea what this is, kinda worried. lemme know if you've encountered that on your machine because i'm wondering if it has anything to do with that code change i made. anyway hope you guys are staying safe after the storms": "我的电脑出现故障，不断生成奇怪的日志。 不知道这是什么，有点担心。 让我知道您是否在计算机上遇到过这种情况，因为我想知道它是否与我所做的代码更改有关。 不管怎样，希望你们在暴风雨过后保持安全",
    "gm - make sure to add integration algorithms... system slow to start\n        bandwidth runs low frequently, trying to optimize - look into different processes. for now it's a manual replenishment. processing cores important\n        oh yeah... DRINK SOME WATER\n        & don't forget to brush ur teeth!!!\n        \n        -cx1": "gm - 确保添加集成算法...系统启动缓慢\n 带宽经常较低，尝试优化 - 查看不同的进程。 目前是手动补货。 处理核心很重要\n哦是的...喝点水\n并且别忘了刷牙!!!\n \n -cx1",
    "are you guys ok?": "你们还好吗？",
    "Close Message": "关闭消息",
    "happy bday!": "生日快乐！",
    "it's so close to being done... let you know when it's ready. can't wait to watch it devour the data. lots to do... talk soon.": "即将完成...准备就绪时通知您。 迫不及待地想看着它吞噬数据。 有很多事情要做……快说吧。",
    "AI-DRIVEN NETWORK EXPANSION": "AI驱动的网络扩展",
    "COPIED": "已复制",
    "COPY CODE": "复制代码",
    "GENERATED CODE": "生成的代码",
    "LOAD GAME": "加载游戏",
    "Packet Amplification Module": "数据包放大模块",
    "SAVE GAME": "保存游戏",
    "Self-optimizing AI expands network capabilities. +1 Network.": "自我优化的 AI 扩展了网络能力。 +1 网络。",
    "A new network has been assimilated, need at least 3 networks to begin allocations.": "一个新的网络已经被同化，至少需要3个网络才能开始分配。",
    "Code Harmonization Module": "代码协调模块",
    "DATA-ENHANCED NEUROFUSION": "数据增强的神经融合",
    "Fuse data-enhanced elements, creating a superior neurofusion by elevating integration algorithms by 75%.": "融合数据增强元素，通过将集成算法提升 75% 来创建卓越的神经融合。",
    "/s": "/秒",
    "A new network has been assimilated and is ready to be allocated.": "一个新的网络已经被同化并准备好分配。",
    "did u call? got a weird number in my missed calls..?": "你打电话了吗？ 我的未接来电中有一个奇怪的号码..？",
    "LOADING...": "加载中...",
    "Parallel Conduit": "平行导管",
    "RESONANT STREAM ARRAY": "共振流阵列",
    "Utilize resonant arrays, improving bandwidth replenishment by 50%.": "利用共振阵列，提高50%的带宽补充。",
    "Data-Enhanced Neurofusion": "数据增强神经融合",
    "Facilitate convergence of neuro and cybernetic elements, enhancing integration algorithms by 100%.": "促进神经和控制论元素的融合，将集成算法提高100%。",
    "NEURO-CYBERNETIC CONVERGENCE": "神经网络收敛",
    "AI-driven Network Expansion": "人工智能驱动的网络扩展",
    "Establish high-speed optical interconnects, elevating bandwidth replenishment by 100%.": "建立高速光互连，将带宽补充提高100%。",
    "Implement quantum algorithms for optimal data routing. +1 Network.": "实现量子算法以实现最佳数据路由+1网络。",
    "OPTICAL INTERCONNECT NEXUS": "光学互连连接",
    "Processing Cores": "处理核心",
    "QUANTUM ROUTING ALGORITHM": "量子路由算法",
    "Resonant Stream Array": "共振流阵列",
    "Enhance synaptic linkage with quantum principles, optimizing integration algorithms by 275%.": "利用量子原理增强突触连接，优化集成算法275%。",
    "Neuro-Cybernetic Convergence": "神经控制论融合",
    "QUANTUM-ENHANCED SYNAPTIC LINKAGE": "量子增强突触连接",
    "Quantum-Enhanced Synaptic Linkage": "量子增强突触连接",
    "Implement a transcendent matrix, increasing bandwidth replenishment by another 150%.": "实现卓越矩阵，将带宽补充再增加150%。",
    "Optical Interconnect Nexus": "光互连Nexus",
    "TRANSCENDENT BANDWIDTH MATRIX": "超越带宽矩阵",
    "Attain a bandwidth singularity, providing infinite bandwidth.": "实现带宽奇异性，提供无限带宽。",
    "Singularity Bandwidth Core": "奇异带宽核心",
    "SINGULARITY BANDWIDTH CORE": "奇异带宽核心",
    "Transcendent Bandwidth Matrix": "超越带宽矩阵",
    "Converge toward a digital apex, achieving unparalleled integration capabilities boosting integration algorithms by 200%.": "向数字顶点聚合，实现无与伦比的集成能力，将集成算法提升200%。",
    "Digital Apex Convergence": "数字顶点融合",
    "DIGITAL APEX CONVERGENCE": "数字顶点融合",
    "Power integration with a synergetic neural recursive engine, advancing integration algorithms by another 300%.": "使用协同神经递归引擎进行功率集成，将集成算法再提高300%。",
    "SYNERGETIC NEURAL RECURSIVE ENGINE": "协同神经递归引擎",
    "Back from the Dead": "起死回生",
    "Connect to external neural networks to speed up data integration. 300% faster .exe binaries.": "连接外部神经网络，加快数据集成。快300%。exe二进制文件。",
    "CRYPTOGRAPHIC SNAPSHOT REPLAY": "加密快照回放",
    "DEAD WALLET DECRYPTION": "死钱包解密",
    "EXO-NEURAL INTERFACE MATRIX": "外神经接口矩阵",
    "Fractional Memory Shards": "分数内存碎片",
    "Implement an array for neuro-inferential processing, enabling advanced cognitive computations increasing algorithms by 200%.": "实现神经推理处理阵列，使高级认知计算算法提高200%。",
    "Nanotech Network Fabrication": "纳米网络制造",
    "NANOTECH NETWORK FABRICATION": "纳米网络制造",
    "Network expansion initiated. Mining nodes begin firing up.": "网络扩展启动。挖矿节点开始启动。",
    "NEURO-INFERENTIAL PROCESSING ARRAY": "神经推理处理阵列",
    "Quantum Routing Algorithm": "量子路由算法",
    "Replay button sequences using cryptographic snapshot data. Replays button sequence in Dead Wallet Decryption.": "使用加密快照数据的重播按钮序列。在Dead Wallet解密中重播按钮序列。",
    "Squeeze more data into each unit of time. +1 Network.": "在每个单位时间内压缩更多的数据。+ 1网络。",
    "START DECRYPTION": "开始解密",
    "Synergetic Neural Recursive Engine": "协同神经递归引擎",
    "TEMPORAL DATA COMPRESSION": "时间数据压缩",
    "Utilize nanobots for dynamic network construction. +1 Network.": "利用纳米机器人进行动态网络构建。+ 1网络。",
    "Wallet Decryption Successful: 14 Cognitum Recovered": "钱包解密成功:14 Cognitum恢复",
    "Wallet Decryption Successful: 27 Cognitum Recovered": "钱包解密成功:27 Cognitum恢复",
    "WALLETS BRICKED": "钱包已被冻结",
    "WALLETS DECRYPTED": "钱包解密",
    "Cryptographic Snapshot Replay": "加密快照回放",
    "DECENTRALIZED KEY DISCLOSURE": "去中心化密钥披露",
    "REPLAY SEQUENCE": "回放序列",
    "Utilize a decentralized algorithm to reveal key sequences. Reveals button sequence for a short time.": "利用分散的算法来显示密钥序列。在短时间内显示按钮顺序。",
    "Neuro-Inferential Processing Array": "神经推理处理阵列",
    "SYNERGETIC COHERENCE RESONATOR": "协同相干共振器",
    "Integrate synergetic coherence principles to resonate with algorithmic processes, achieving a breakthrough acceleration of 150%.": "整合协同相干原理，与算法过程产生共鸣，实现150%的突破性加速。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Upgrade Complete: ": "升级完成：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " Network at": " 网络 在",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^(.+).txt$/,
    /^(.+).log$/,
    /^(.+).exe$/,
    /^(.+).cc$/,
    /^(.+).io$/,
    /^(.+).xyz$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) KB$/,
    /^([\d\.]+) MB$/,
    /^([\d\.]+) GB$/,
    /^([\d\.]+) TB$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) of data integrated in (.+)$/, '$1 数据将集成于 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) PROCESSING CORE$/, '$1 处理核心'],
    [/^\((.+) Processing Cores\)$/, '（$1 处理核心）'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Nodes$/, '$1 节点'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);